import type {
  KnowledgeCluster,
  KnowledgeEdge,
  KnowledgeNode,
} from "./types";

/**
 * Knowledge Constellation — 7 Cluster-Sterne + Satelliten, feste Positionen
 * (kein Force-Graph: deterministisch, designbar, mobil beherrschbar).
 * Koordinaten in einem 0–100-Viewport, werden im SVG skaliert.
 * Jeder Satellit trägt einen `proof` — die Konstellation ist eine Landkarte
 * der TATSÄCHLICHEN Praxis, nicht eine Behauptungswolke.
 */

export const clusters: KnowledgeCluster[] = [
  { id: "orchestration", label: "LLM-Orchestrierung", x: 27, y: 20, blurb: "Mehrere Modelle und Agenten gezielt zusammenspielen lassen." },
  { id: "local", label: "Lokale LLMs", x: 73, y: 17, blurb: "Modelle auf eigener Hardware betreiben — datenschutzkonform." },
  { id: "multiagent", label: "Multi-Agent-Systeme", x: 50, y: 39, blurb: "Aufgaben auf spezialisierte, sich gegenseitig prüfende Agenten verteilen." },
  { id: "mcp", label: "MCP-Protokoll", x: 17, y: 54, blurb: "Werkzeuge und Daten über das Model-Context-Protocol anbinden." },
  { id: "memory", label: "RAG & Memory", x: 82, y: 53, blurb: "Wissen abrufbar machen — persistentes Gedächtnis und Retrieval." },
  { id: "prompting", label: "Prompt Engineering", x: 34, y: 80, blurb: "Modelle gezielt steuern und ihre Ausgaben verlässlich formen." },
  { id: "automation", label: "Automatisierung", x: 70, y: 82, blurb: "Wiederkehrende Abläufe per KI auf Knopfdruck erledigen." },
  { id: "interests", label: "Interessen & Forschung", x: 52, y: 60, blurb: "Woran ich gerade tüftle und forsche." },
  { id: "infra", label: "Infrastruktur & Betrieb", x: 12, y: 33, blurb: "Eigene Server, Deployment und Systeme, auf denen die KI-Lösungen laufen." },
  { id: "quality", label: "Qualität & Testing", x: 88, y: 73, blurb: "Software absichern: von E2E-Tests über Fuzzing bis zu Performance-Audits." },
  { id: "security", label: "Security & Datenschutz", x: 8, y: 80, blurb: "Auth, Secrets-Hygiene und DSGVO-Praxis — Sicherheit als Gewohnheit, nicht als Nachgedanke." },
];

export const nodes: KnowledgeNode[] = [
  // ── LLM-Orchestrierung ──
  {
    id: "o-claudecode",
    label: "Claude Code",
    clusterId: "orchestration",
    x: 14,
    y: 11,
    level: "satellite",
    desc: "Täglicher Treiber meines gesamten Workflows — gesteuert über Hooks, Skills und Commands.",
    proof: { text: "Mein Setup im Detail", href: "#setup" },
  },
  {
    id: "o-routing",
    label: "Modell-Routing",
    clusterId: "orchestration",
    x: 35,
    y: 9,
    level: "satellite",
    desc: "Anfragen je nach Komplexität und Datensensibilität an Cloud- oder lokale Modelle leiten.",
    proof: { text: "Konzept im Lab", href: "#lab" },
  },
  {
    id: "o-cascade",
    label: "Agenten-Kette",
    clusterId: "orchestration",
    x: 30,
    y: 30,
    level: "satellite",
    desc: "Plan → Implement → Review als koordinierte Kette spezialisierter Modelle.",
    proof: { text: "Cascade-Bot", href: "/projekte/cascade-bot" },
  },

  // ── Lokale LLMs ──
  {
    id: "l-ollama",
    label: "Ollama",
    clusterId: "local",
    x: 86,
    y: 9,
    level: "satellite",
    desc: "Lokale Inferenz auf eigenem Server — läuft 24/7 auf meinem VPS.",
    proof: { text: "DocuFlow nutzt es", href: "/projekte/docuflow" },
  },
  {
    id: "l-vision",
    label: "Vision-OCR",
    clusterId: "local",
    x: 62,
    y: 11,
    level: "satellite",
    desc: "Vision-OCR für deutsche Geschäftsdokumente — hybrid: lokale Stufe im Normalfall, Qwen3-VL als Gegencheck über Ollama Cloud, EU-Cloud (Mistral) als Option und Fallback bei lokaler Last.",
    proof: { text: "DocuFlow", href: "/projekte/docuflow" },
  },
  {
    id: "l-privacy",
    label: "On-Premise-Datenschutz",
    clusterId: "local",
    x: 88,
    y: 27,
    level: "satellite",
    desc: "Sensible Daten müssen das Haus nicht verlassen — wahlweise komplett lokal, der entscheidende Hebel für KMU.",
    proof: { text: "Hintergrund im Lab", href: "#lab" },
  },

  // ── Multi-Agent-Systeme ──
  {
    id: "m-pir",
    label: "Plan·Implement·Review",
    clusterId: "multiagent",
    x: 50,
    y: 28,
    level: "satellite",
    desc: "Rollenbasierte Kette: jedes Modell macht, was es am besten kann.",
    proof: { text: "Cascade-Bot", href: "/projekte/cascade-bot" },
  },
  {
    id: "m-verify",
    label: "Adversariale Verifikation",
    clusterId: "multiagent",
    x: 64,
    y: 36,
    level: "satellite",
    desc: "Mehrere unabhängige Prüf-Agenten pro Befund — perspektiven-divers statt redundant.",
  },
  {
    id: "m-roles",
    label: "Rollen-Spezialisierung",
    clusterId: "multiagent",
    x: 40,
    y: 48,
    level: "satellite",
    desc: "Planner, Implementer und Reviewer mit klar geschnittenen Zuständigkeiten.",
    proof: { text: "Cascade-Bot", href: "/projekte/cascade-bot" },
  },

  // ── MCP-Protokoll ──
  {
    id: "mcp-rlm",
    label: "Eigener RLM-Server",
    clusterId: "mcp",
    x: 8,
    y: 44,
    level: "satellite",
    desc: "Selbst gebauter MCP-Server in Python — bringt persistentes Memory in jede Session.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "mcp-fleet",
    label: "13 MCP-Server",
    clusterId: "mcp",
    x: 30,
    y: 60,
    level: "satellite",
    desc: "Von Git über Filesystem bis Linear — Werkzeuge, die der Assistent direkt bedient.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "mcp-cascade",
    label: "Cascade als MCP",
    clusterId: "mcp",
    x: 10,
    y: 66,
    level: "satellite",
    desc: "Agenten-Orchestrierung sauber als MCP-Server gekapselt.",
    proof: { text: "Cascade-Bot", href: "/projekte/cascade-bot" },
  },

  // ── RAG & Memory ──
  {
    id: "mem-rlm",
    label: "RLM-System",
    clusterId: "memory",
    x: 92,
    y: 45,
    level: "satellite",
    desc: "Selbst gebautes Memory: 730+ Insights, sessionübergreifend abrufbar.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "mem-search",
    label: "BM25 + semantisch",
    clusterId: "memory",
    x: 70,
    y: 50,
    level: "satellite",
    desc: "Hybride Suche über das Memory — präzise Begriffe und semantische Nähe kombiniert.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "mem-chunks",
    label: "Session-Chunks",
    clusterId: "memory",
    x: 90,
    y: 67,
    level: "satellite",
    desc: "Ganze Arbeitssitzungen werden verdichtet gespeichert und später wieder eingespielt.",
    proof: { text: "Im Setup", href: "#setup" },
  },

  // ── Prompt Engineering ──
  {
    id: "p-suggest",
    label: "KI-Vorschlags-System",
    clusterId: "prompting",
    x: 28,
    y: 88,
    level: "satellite",
    desc: "Strukturierte Prompts erzeugen Regel-Vorschläge mit Begründung und Feedback-Loop.",
    proof: {
      text: "Lieferschein-Processor",
      href: "/projekte/lieferschein-processor",
    },
  },
  {
    id: "p-structured",
    label: "Strukturierte Outputs",
    clusterId: "prompting",
    x: 48,
    y: 86,
    level: "satellite",
    desc: "JSON-Schemata erzwingen verlässliche, weiterverarbeitbare Modell-Antworten.",
    proof: { text: "DocuFlow-Extraktion", href: "/projekte/docuflow" },
  },
  {
    id: "p-system",
    label: "System-Prompts & Guardrails",
    clusterId: "prompting",
    x: 24,
    y: 70,
    level: "satellite",
    desc: "Verhalten gezielt formen — und über Hooks technisch absichern.",
    proof: { text: "Hook-Pipeline", href: "#setup" },
  },

  // ── Automatisierung ──
  {
    id: "a-pipeline",
    label: "Dokumenten-Pipelines",
    clusterId: "automation",
    x: 68,
    y: 92,
    level: "satellite",
    desc: "Wiederkehrende Büroprozesse laufen auf Knopfdruck statt von Hand.",
    proof: {
      text: "Lieferschein-Processor",
      href: "/projekte/lieferschein-processor",
    },
  },
  {
    id: "a-hooks",
    label: "Hook-Pipeline",
    clusterId: "automation",
    x: 84,
    y: 88,
    level: "satellite",
    desc: "16 Skripte über 6 Events — Disziplin und Wiederholbarkeit erzwungen statt erhofft.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "a-sort",
    label: "Selbstlernende Sortierung",
    clusterId: "automation",
    x: 60,
    y: 74,
    level: "satellite",
    desc: "Aus bestätigten Extraktionen entstehen automatisch neue Templates.",
    proof: { text: "DocuFlow", href: "/projekte/docuflow" },
  },

  // ── Interessen & Forschung ──
  {
    id: "in-hardware",
    label: "Lokale KI-Hardware",
    clusterId: "interests",
    x: 43,
    y: 54,
    level: "satellite",
    desc: "GPUs, ARM-Server und Edge-Geräte — was lokale Inferenz praktisch und bezahlbar macht. Mein VPS und eine 1080-Ti-Workstation sind die Spielwiese.",
    proof: { text: "Mein Setup", href: "#setup" },
  },
  {
    id: "in-mobile",
    label: "KI auf mobilen Geräten",
    clusterId: "interests",
    x: 61,
    y: 53,
    level: "satellite",
    desc: "Modelle und Agenten, die auf dem Handy laufen oder von unterwegs gesteuert werden — KI, die nicht am Schreibtisch klebt.",
  },
  {
    id: "in-unified",
    label: "Unified Memory & GPU-Stacks",
    clusterId: "interests",
    x: 67,
    y: 64,
    level: "satellite",
    desc: "Warum DGX Spark und Mac Studio für große lokale Modelle spannend sind: gemeinsamer Speicher für CPU und GPU statt harter VRAM-Grenzen — und wann ein klassischer Grafikkarten-Stack trotzdem gewinnt. Hardware-Vergleiche sind bei mir Freizeit.",
  },
  {
    id: "in-benchmarks",
    label: "Open-Weight-Modellvergleich",
    clusterId: "interests",
    x: 52,
    y: 70,
    level: "satellite",
    desc: "Offene Modelle (Kimi, DeepSeek, GLM …) mit eigenen Benchmarks vergleichen, statt Marketing-Zahlen zu glauben — Tool-Format-Treue, Reasoning, Kosten.",
    proof: { text: "Konzept im Lab", href: "#lab" },
  },

  // ── LLM-Orchestrierung (Ausbau 2026-06-10, RLM-belegt) ──
  {
    id: "o-workflows",
    label: "ultracode-Workflows",
    clusterId: "orchestration",
    x: 20,
    y: 24,
    level: "satellite",
    desc: "Fan-out-Workflows mit parallelen Agenten und adversarialer Verifikation — Recherche, Audits und sogar die Screenshots dieser Seite liefen so.",
    proof: { text: "Making-of dieser Seite", href: "#making-of" },
  },
  {
    id: "o-goals",
    label: "Roadmaps mit Akzeptanz-Gates",
    clusterId: "orchestration",
    x: 38,
    y: 22,
    level: "satellite",
    desc: "Mehrwöchige Projekt-Roadmaps mit messbaren Akzeptanz-Tests und Definition-of-Done, die Agenten Sprint für Sprint abarbeiten.",
    proof: { text: "PA-Streaming-Hub", href: "/projekte/pa-streaming-hub" },
  },

  // ── Multi-Agent (Ausbau) ──
  {
    id: "m-persona",
    label: "24/7-Agent mit Persona",
    clusterId: "multiagent",
    x: 58,
    y: 45,
    level: "satellite",
    desc: "Ein dauerhafter Agent auf dem eigenen Server — mit definierten Betriebsregeln, Persona und Zugriff aufs geteilte Memory.",
    proof: { text: "Hermes im Lab", href: "#lab" },
  },

  // ── Lokale LLMs (Ausbau) ──
  {
    id: "l-whisper",
    label: "Sprache → Text lokal",
    clusterId: "local",
    x: 75,
    y: 30,
    level: "satellite",
    desc: "faster-whisper auf dem CPU-only-ARM-Server: Telegram-Sprachnachrichten werden lokal transkribiert, ohne Cloud-Umweg.",
    proof: { text: "Hermes im Lab", href: "#lab" },
  },

  // ── RAG & Memory (Ausbau) ──
  {
    id: "mem-graph",
    label: "Knowledge-Graph",
    clusterId: "memory",
    x: 74,
    y: 62,
    level: "satellite",
    desc: "Neben dem RLM ein strukturierter Entitäten-Graph mit Projekten, Regeln und Anti-Patterns — per Hook-Pipeline aktuell gehalten.",
    proof: { text: "Im Setup", href: "#setup" },
  },

  // ── Automatisierung (Ausbau) ──
  {
    id: "a-skills",
    label: "Eigene Skills & Commands",
    clusterId: "automation",
    x: 56,
    y: 88,
    level: "satellite",
    desc: "Wiederkehrende Abläufe als eigene Claude-Code-Skills und Slash-Commands gekapselt — vom Recherche-Dokument bis zum Umgebungs-Check.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "a-xplat",
    label: "Cross-Platform-Hooks",
    clusterId: "automation",
    x: 76,
    y: 95,
    level: "satellite",
    desc: "Die PowerShell-Hook-Pipeline läuft identisch auf Windows, WSL und Linux-Server — abgesichert durch eine eigene Smoketest-Suite.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "a-cron",
    label: "Agenten-Monitoring",
    clusterId: "automation",
    x: 90,
    y: 80,
    level: "satellite",
    desc: "Laufende Remote-Sessions werden per Cron überwacht: Idle-Status, Token-Verbrauch und Repo-Zustand im Blick.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "a-telegram",
    label: "Telegram-Bots im Betrieb",
    clusterId: "automation",
    x: 52,
    y: 95,
    level: "satellite",
    desc: "Zwei produktive Telegram-Bots (Agenten-Steuerung und Gateway) als Dauerdienste — inklusive Webhook-/Polling-Debugging.",
    proof: { text: "Cascade-Bot", href: "/projekte/cascade-bot" },
  },

  // ── Infrastruktur & Betrieb (NEU 2026-06-10) ──
  {
    id: "i-sync",
    label: "Multi-Machine-Sync",
    clusterId: "infra",
    x: 5,
    y: 25,
    level: "satellite",
    desc: "Zwei PCs, WSL und ein VPS halten Skills, Hooks und Memory synchron — newer-wins mit Backups; aus einem Datenverlust wurden eigene Sync-Regeln.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "i-tls",
    label: "TLS auf nackter IP",
    clusterId: "infra",
    x: 19,
    y: 22,
    level: "satellite",
    desc: "Let's-Encrypt-IP-Zertifikat (Kurzläufer-Profil) via Caddy für genau diese Seite — inklusive der SNI-Falle, die IP-Hosting mitbringt.",
    proof: { text: "Making-of", href: "#making-of" },
  },
  {
    id: "i-systemd",
    label: "systemd & Cloud-Firewall",
    clusterId: "infra",
    x: 6,
    y: 42,
    level: "satellite",
    desc: "Portfolio, Agenten und Bots laufen als gehärtete systemd-Dienste auf Oracle Cloud — Firewall doppelt gedacht (Cloud-Ebene + iptables).",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "i-nixos",
    label: "NixOS deklarativ",
    clusterId: "infra",
    x: 22,
    y: 40,
    level: "satellite",
    desc: "Eine komplette Appliance als Code: Flake, eigenes Modul, Impermanence — reproduzierbar neu bauen statt von Hand pflegen.",
    proof: { text: "PA-Streaming-Hub", href: "/projekte/pa-streaming-hub" },
  },
  {
    id: "i-pipewire",
    label: "PipeWire-DSP",
    clusterId: "infra",
    x: 13,
    y: 30,
    level: "satellite",
    desc: "Audio-Filterketten mit LSP-Plugins: Autogain, Loudness-Profile und saubere Signalwege für den PA-Verleih.",
    proof: { text: "PA-Streaming-Hub", href: "/projekte/pa-streaming-hub" },
  },

  // ── Qualität & Testing (NEU 2026-06-10) ──
  {
    id: "q-e2e",
    label: "Playwright E2E & Visual",
    clusterId: "quality",
    x: 82,
    y: 66,
    level: "satellite",
    desc: "Test-Suiten, die die echte App bedienen — vom PDF-Upload in Streamlit bis zu Visual-Sweeps über alle Viewports.",
    proof: { text: "Lieferschein-Processor", href: "/projekte/lieferschein-processor" },
  },
  {
    id: "q-fuzz",
    label: "Fuzz-Testing",
    clusterId: "quality",
    x: 94,
    y: 68,
    level: "satellite",
    desc: "Eine Fuzzing-Suite fürs Backend fand zwei echte Crash-Bugs, bevor es ein Nutzer tat.",
    proof: { text: "PA-Streaming-Hub", href: "/projekte/pa-streaming-hub" },
  },
  {
    id: "q-vitals",
    label: "Lighthouse & Web Vitals",
    clusterId: "quality",
    x: 88,
    y: 80,
    level: "satellite",
    desc: "Diese Seite: mobil von Score 74 auf 90+ gebracht — per LCP-Analyse statt Raten, CLS auf 0 gehalten.",
    proof: { text: "Making-of", href: "#making-of" },
  },

  // ── Security & Datenschutz (NEU 2026-06-10) ──
  {
    id: "s-auth",
    label: "Auth-Stack selbst gebaut",
    clusterId: "security",
    x: 4,
    y: 72,
    level: "satellite",
    desc: "Argon2-gehashte Zugangscodes, JWT-Session-Cookies, Rate-Limiting mit Proxy-Header-Fallen — das Gate, das diese Seite schützt.",
    proof: { text: "Making-of", href: "#making-of" },
  },
  {
    id: "s-secrets",
    label: "Secrets-Hygiene",
    clusterId: "security",
    x: 14,
    y: 76,
    level: "satellite",
    desc: "Tokens nur in restriktiven Dateien, nie im Chatverlauf; eigene Repo-Audits haben echte Leaks gefunden — und zur Rotation geführt.",
    proof: { text: "Im Setup", href: "#setup" },
  },
  {
    id: "s-dsgvo",
    label: "DSGVO in der Praxis",
    clusterId: "security",
    x: 8,
    y: 88,
    level: "satellite",
    desc: "Auftragsverarbeitung nach Art. 28 konkret durchdacht: EU-Cloud-OCR mit AVV oder komplett lokal ohne Dienstleister — dokumentiert im Projekt.",
    proof: { text: "Ordio-Perso-CSV", href: "/projekte/ordio-csv" },
  },
];

/** Verbindungslinien zwischen verwandten Clustern (die „Sternbilder"). */
export const edges: KnowledgeEdge[] = [
  { from: "orchestration", to: "multiagent" },
  { from: "orchestration", to: "local" },
  { from: "orchestration", to: "prompting" },
  { from: "multiagent", to: "mcp" },
  { from: "multiagent", to: "memory" },
  { from: "mcp", to: "memory" },
  { from: "local", to: "memory" },
  { from: "prompting", to: "automation" },
  { from: "automation", to: "memory" },
  { from: "mcp", to: "prompting" },
  { from: "interests", to: "local" },
  { from: "interests", to: "multiagent" },
  { from: "interests", to: "memory" },
  { from: "infra", to: "automation" },
  { from: "infra", to: "local" },
  { from: "quality", to: "automation" },
  { from: "security", to: "infra" },
  { from: "security", to: "local" },
];

export const clustersById = new Map(clusters.map((c) => [c.id, c]));
